services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devpulsefrontprod
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped